global: &global
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost

development:
  <<: *global
  database: blackprofessionals_development

test:
  <<: *global
  database: blackprofessionals_test

production:
  <<: *global
  database: blackprofessionals_production
